"use client";
import {useEffect,useMemo,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"https://autonomous-web-company-production.up.railway.app";
type Project={id:number;name:string;domain:string;dry_run:boolean;active:boolean};
type Employee={id?:number;name:string;role:string;agent?:string};
type Settings={project:Project;employees?:Employee[];connections:{github:boolean;vercel:boolean;google:{connected:boolean;search_console:boolean;analytics:boolean}}};
type Analytics={period_days:number;gsc:{configured:boolean;clicks:number;impressions:number;ctr:number;opportunities:any[]};ga4:{configured:boolean;users:number;sessions:number;engagement_rate:number}};
async function json<T>(u:string,i?:RequestInit){const r=await fetch(u,i);if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json() as Promise<T>}
export default function Page(){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<number>(),[settings,setSettings]=useState<Settings>(),[analytics,setAnalytics]=useState<Analytics>(),[runs,setRuns]=useState<any[]>([]),[status,setStatus]=useState<any>(),[loading,setLoading]=useState(true),[running,setRunning]=useState(false),[vercelBusy,setVercelBusy]=useState(false),[error,setError]=useState("");
 async function load(id?:number){setLoading(true);try{setError("");const ps=await json<Project[]>(`${API}/api/projects`);setProjects(ps);const target=id||selected||ps[0]?.id;if(!target){setSettings(undefined);setAnalytics(undefined);setRuns([]);setLoading(false);return}const base=ps.find(p=>p.id===target)||ps[0];setSelected(base.id);const results=await Promise.allSettled([json<Settings>(`${API}/api/projects/${base.id}/settings`),json<Analytics>(`${API}/api/projects/${base.id}/analytics`),json<any[]>(`${API}/api/projects/${base.id}/runs`),json<any>(`${API}/api/status`)]);const [st,a,r,bs]=results;if(st.status==="fulfilled")setSettings(st.value);else setError(st.reason instanceof Error?st.reason.message:"تعذر تحميل إعدادات المشروع");if(a.status==="fulfilled")setAnalytics(a.value);if(r.status==="fulfilled")setRuns(r.value);if(bs.status==="fulfilled")setStatus(bs.value)}catch(e){setError(e instanceof Error?e.message:"تعذر الاتصال بالعقل")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function runBrain(){if(!selected)return;setRunning(true);try{await json(`${API}/api/projects/${selected}/run`,{method:"POST"});await load(selected)}catch(e){setError(e instanceof Error?e.message:"فشل تشغيل العقل")}finally{setRunning(false)}}
 function connectVercel(){if(!selected||vercelBusy)return;setVercelBusy(true);const url=`${API}/api/projects/${selected}/vercel/oauth/start`;const w=window.open(url,"vercel-marketplace","width=560,height=820");if(!w){window.location.href=url;return}let attempts=0;const timer=window.setInterval(async()=>{attempts++;try{const fresh=await json<Settings>(`${API}/api/projects/${selected}/settings`);setSettings(fresh);if(fresh.connections.vercel){window.clearInterval(timer);setVercelBusy(false);if(!w.closed)w.close()}}catch{}if(w.closed&&attempts>2){window.clearInterval(timer);setVercelBusy(false);load(selected)}if(attempts>90){window.clearInterval(timer);setVercelBusy(false)}},2000)}
 const online=status?.status==="online",autonomous=!settings?.project.dry_run,connections=settings?.connections,project=settings?.project,google=connections?.google;
 const employees=settings?.employees||[];const completedRuns=runs.filter(r=>r.status==="cycle_complete").length;
 const agentRows=employees.length?employees.slice(0,5):[];
 const vercelConnected=!!connections?.vercel;
 const projectInitial=project?.name?.slice(0,1).toUpperCase()||"A";
 const growth=useMemo(()=>({clicks:analytics?.gsc.configured?analytics.gsc.clicks:0,impressions:analytics?.gsc.configured?analytics.gsc.impressions:0,users:analytics?.ga4.configured?analytics.ga4.users:0}),[analytics]);
 return <div className="companyShell" dir="rtl">
  <aside className="companySidebar">
   <div className="companyBrand"><div className="brandNetwork"><span/><span/><span/><b/></div><div><strong>AUTONOMOUS</strong><small>WEB COMPANY</small></div></div>
   <div className="sidebarLabel">مركز الشركة</div>
   <nav><a className="companyNav active" href="/"><Icon name="grid"/><span>نظرة عامة</span></a><a className="companyNav" href="/settings?tab=employees"><Icon name="bot"/><span>الموظفون</span></a><a className="companyNav" href="/settings?tab=connections"><Icon name="plug"/><span>الاتصالات</span></a><a className="companyNav" href="/settings?tab=models"><Icon name="spark"/><span>نماذج الذكاء</span></a><a className="companyNav" href="/settings?tab=google"><Icon name="search"/><span>Google & SEO</span></a><a className="companyNav" href="/#activity"><Icon name="activity"/><span>سجل النشاط</span></a></nav>
   <div className="sidebarFooter"><a className="companyNav" href="/settings"><Icon name="settings"/><span>الإعدادات</span></a><div className="brainStatus"><i className={online?"on":""}/><div><strong>{online?"العقل متصل":"جاري الاتصال"}</strong><small>{autonomous?"تنفيذ مستقل":"Dry Run"}</small></div></div></div>
  </aside>
  <main className="companyMain">
   <header className="companyHeader"><div><div className="companyCrumb"><i/> مركز التحكم <b>/</b> المشروع النشط</div><h1>AUTONOMOUS WEB COMPANY</h1><p>منصة تشغيل شركة ويب ذاتية الإدارة — العقل يخطط، الموظفون ينفذون، والنتائج تُراقب تلقائياً.</p></div><div className="headerActions"><span className={`connectionPill ${online?"on":""}`}><i/>{online?"العقل متصل":"جاري الاتصال"}</span><select value={selected||""} onChange={e=>load(Number(e.target.value))}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></header>
   {error&&<div className="companyAlert"><strong>تعذر تنفيذ الطلب</strong><span>{error}</span></div>}
   {loading?<div className="companyCard loadingCompany"><Spinner/> جاري تحميل مركز الشركة…</div>:!project?<div className="companyCard emptyCompany"><span className="heroKicker">FIRST PROJECT</span><h2>أنشئ أول مشروع للشركة</h2><p>بعد إنشاء المشروع يمكنك ربط Vercel وGitHub وGoogle وتشغيل العقل فعلياً.</p><a href="/settings">فتح الإعدادات</a></div>:<>
    <section className="orchestrationLayout">
      <div className="companyCard orchestration"><div className="sectionHead"><div><span className="heroKicker">AUTONOMOUS ORCHESTRATION</span><h2>العقل يدير الشركة</h2><p>هدف المشروع والموظفون والاتصالات في دورة تشغيل واحدة.</p></div><button className="primaryButton" disabled={running||!online} onClick={runBrain}>{running?<><Spinner/> جاري التشغيل</>:"تشغيل دورة العقل"}</button></div>
       <div className="orbitStage">
        <div className="orbit orbitOne"/><div className="orbit orbitTwo"/><div className="orbitCore"><span>GLOBAL COMPANY GOAL</span><strong>{project.name}</strong><small>{autonomous?"التنفيذ المستقل مفعّل":"Dry Run مفعّل"}</small></div>
        <AgentNode pos="ceo" icon="↗" title="CEO Agent" sub="التخطيط والقرارات" tone="green"/>
        <AgentNode pos="developer" icon="&lt;/&gt;" title="Developer Agent" sub="الكود والنشر" tone="blue"/>
        <AgentNode pos="marketing" icon="◈" title="Marketing Agent" sub="النمو والمحتوى" tone="green"/>
        <AgentNode pos="support" icon="◉" title="Support Agent" sub="المراقبة والدعم" tone="blue"/>
       </div>
      </div>
      <aside className="companyCard livePanel"><div className="sectionHead compact"><div><span className="heroKicker">REAL DATA</span><h3>الأداء الفعلي</h3></div><span className="liveBadge"><i/> LIVE</span></div><div className="statGrid"><Stat label="نقرات البحث" value={analytics?.gsc.configured?growth.clicks.toLocaleString("en-US"):"—"} source={analytics?.gsc.configured?"Search Console":"غير متصل"}/><Stat label="مرات الظهور" value={analytics?.gsc.configured?growth.impressions.toLocaleString("en-US"):"—"} source={analytics?.gsc.configured?"Search Console":"غير متصل"}/><Stat label="المستخدمون" value={analytics?.ga4.configured?growth.users.toLocaleString("en-US"):"—"} source={analytics?.ga4.configured?"Analytics 4":"غير متصل"}/><Stat label="دورات مكتملة" value={String(completedRuns)} source="Execution log"/></div><div className="miniActivity"><h4>آخر نشاط</h4>{runs.length?runs.slice(0,3).map((r,i)=><div className="miniActivityRow" key={r.id}><i className={r.status==="cycle_complete"?"green":"blue"}/><div><strong>دورة #{r.id}</strong><span>{r.status}</span></div><small>{r.finished_at?new Date(r.finished_at).toLocaleString("ar"):"قيد التنفيذ"}</small></div>):<div className="noData">لا توجد دورات تشغيل بعد.</div>}</div></aside>
    </section>
    <section className="companyCard agentsPanel"><div className="sectionHead"><div><span className="heroKicker">AGENT MANAGEMENT</span><h2>فريق الموظفين</h2><p>هذه القائمة مبنية على الموظفين المحفوظين فعلياً في المشروع.</p></div><a className="outlineButton" href="/settings?tab=employees">إدارة الموظفين</a></div>{agentRows.length?<div className="agentTable"><div className="agentTableHead"><span>الموظف</span><span>الدور</span><span>النموذج</span><span>الحالة</span><span/></div>{agentRows.map((e,i)=><div className="agentRow" key={e.id||i}><div className="agentIdentity"><span className={`agentIcon ${i%2?"blue":"green"}`}>{e.name.slice(0,1)}</span><strong>{e.name}</strong></div><span>{e.role}</span><span>{e.agent||"—"}</span><span className="agentState"><i/> جاهز</span><a href="/settings?tab=employees">•••</a></div>)}</div>:<div className="noAgents"><div className="agentEmptyIcon">+</div><div><strong>لا يوجد موظفون بعد</strong><span>أضف أول وكيل AI ليبدأ العقل بإسناد المهام إليه.</span></div><a href="/settings?tab=employees">إضافة موظف</a></div>}</section>
    <section className="bottomGrid"><div className="companyCard connectionPanel"><div className="sectionHead compact"><div><span className="heroKicker">LIVE CONNECTIONS</span><h3>الاتصالات الحقيقية</h3></div><a className="miniLink" href="/settings?tab=connections">إدارة الكل</a></div><Connection name="GitHub" on={!!connections?.github} icon="GH"/><Connection name="Vercel" on={vercelConnected} icon="V" action={!vercelConnected?connectVercel:undefined} busy={vercelBusy}/><Connection name="Search Console" on={!!google?.search_console} icon="G"/><Connection name="Analytics 4" on={!!google?.analytics} icon="A"/></div><div className="companyCard opportunityPanel"><div className="sectionHead compact"><div><span className="heroKicker">SEO INTELLIGENCE</span><h3>فرص البحث</h3></div><span className="muted">{analytics?.period_days||28} يوم</span></div>{google?.search_console&&analytics?.gsc.opportunities.length?<div className="opportunityRows">{analytics.gsc.opportunities.slice(0,4).map((o:any,i)=><div className="opRow" key={i}><b>{String(i+1).padStart(2,"0")}</b><div><strong>{o.query||"استعلام"}</strong><span>{o.page||"صفحة"}</span></div><em>{Math.round(o.impressions||0).toLocaleString("en-US")} ظهور</em></div>)}</div>:<div className="noData">اربط Search Console لعرض فرص SEO حقيقية.</div>}</div></section>
    <section className="companyCard activityPanel" id="activity"><div className="sectionHead compact"><div><span className="heroKicker">ACTIVITY LOG</span><h3>سجل عمليات العقل</h3></div><span className="muted">آخر العمليات</span></div>{runs.length?runs.slice(0,8).map((r:any)=><div className="activityLine" key={r.id}><span className="timelineDot"><i/></span><div><strong>دورة تشغيل #{r.id}</strong><span>{r.status}</span></div><time>{r.finished_at?new Date(r.finished_at).toLocaleString("ar"):"قيد التشغيل"}</time></div>):<div className="noData">لا توجد عمليات مسجلة بعد.</div>}</section>
   </>}
  </main>
 </div>
}
function Icon({name}:{name:string}){const p:any={grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,bot:<><rect x="4" y="6" width="16" height="14" rx="3"/><path d="M12 2v4M8 13h.01M16 13h.01M9 17h6"/></>,plug:<><path d="M8 12h8M12 8v8"/><path d="M7 5v4M17 5v4M7 19v-2a5 5 0 0 1 10 0v2"/></>,spark:<path d="m12 3 1.7 6.3L20 11l-6.3 1.7L12 19l-1.7-6.3L4 11l6.3-1.7L12 3Z"/>,search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,activity:<path d="M3 12h4l2-6 4 12 2-6h6"/>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19 13l2 1-2 3-2-1a8 8 0 0 1-2 1v2h-6v-2a8 8 0 0 1-2-1l-2 1-2-3 2-1a8 8 0 0 1 0-2L3 10l2-3 2 1a8 8 0 0 1 2-1V5h6v2a8 8 0 0 1 2 1l2-1 2 3-2 1a8 8 0 0 1 0 2Z"/></>};return <svg className="companyIcon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}
function AgentNode({pos,icon,title,sub,tone}:{pos:string;icon:string;title:string;sub:string;tone:string}){return <div className={`agentNode ${pos}`}><div className={`nodeIcon ${tone}`}>{icon}</div><strong>{title}</strong><span>{sub}</span></div>}
function Stat({label,value,source}:{label:string;value:string;source:string}){return <div className="liveStat"><span>{label}</span><strong>{value}</strong><small>{source}</small></div>}
function Connection({name,on,icon,action,busy}:{name:string;on:boolean;icon:string;action?:()=>void;busy?:boolean}){return <div className="connectionRow"><div className="connectionIdentity"><span className="connectionIcon">{icon}</span><strong>{name}</strong></div><div className="connectionRight">{on?<span className="connectedLabel"><i/> متصل</span>:action?<button className="connectSmall" disabled={busy} onClick={action}>{busy?<Spinner/>:"ربط الآن"}</button>:<span className="disconnectedLabel">غير متصل</span>}</div></div>}
function Spinner(){return <i className="spinnerCompany"/>}
