"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"https://autonomous-web-company-production.up.railway.app";
async function json<T>(u:string,i?:RequestInit){const r=await fetch(u,i);if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json() as Promise<T>}
type Project={id:number;name:string;domain:string;repo:string;branch:string;goal:string;language:string;dry_run:boolean;active:boolean};
type Settings={project:Project;employees:any[];models:any[];connections:any};
export default function Control(){const[projects,setProjects]=useState<Project[]>([]),[pid,setPid]=useState<number>(),[s,setS]=useState<Settings>(),[auto,setAuto]=useState<any>(),[edit,setEdit]=useState<Project|null>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const load=async(id?:number)=>{try{const ps=await json<Project[]>(`${API}/api/projects`);setProjects(ps);const n=id||pid||ps[0]?.id;if(n){setPid(n);const [ss,aa]=await Promise.all([json<Settings>(`${API}/api/projects/${n}/settings`),json<any>(`${API}/api/projects/${n}/autonomy`)]);setS(ss);setAuto(aa)}}catch(e){setMsg(e instanceof Error?e.message:"تعذر الاتصال بالعقل")}};
 useEffect(()=>{load()},[]);
 async function saveProject(){if(!edit)return;setBusy(true);try{await json(`${API}/api/projects/${edit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(edit)});setMsg("تم حفظ إعدادات المشروع");setEdit(null);await load(edit.id)}catch(e){setMsg(e instanceof Error?e.message:"فشل الحفظ")}finally{setBusy(false)}}
 async function toggleEmployee(e:any){if(!pid)return;setBusy(true);try{await json(`${API}/api/projects/${pid}/employees/${e.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!e.active})});await load(pid)}finally{setBusy(false)}}
 async function toggleModel(m:any){if(!pid)return;setBusy(true);try{await json(`${API}/api/projects/${pid}/models/${m.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!m.active})});await load(pid)}finally{setBusy(false)}}
 const p=s?.project;return <div className="controlPage" dir="rtl"><header className="controlHeader"><div><a href="/" className="backLink">← مركز التحكم</a><span className="eyebrow">COMPANY CONTROL</span><h1>لوحة تحكم الشركة المستقلة</h1><p>كل ما يراه العقل هنا قابل للمراجعة والتعديل من نفس المكان.</p></div><div className="controlActions"><select value={pid||""} onChange={e=>load(+e.target.value)}>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{p&&<button onClick={()=>setEdit({...p})}>تعديل المشروع</button>}</div></header>{msg&&<div className="controlNotice">{msg}</div>}{!p?<div className="controlEmpty">لا يوجد مشروع بعد. <a href="/">أنشئ المشروع من مركز التحكم</a></div>:<>
 <section className="controlHero"><div><span className="eyebrow">الهدف الرئيسي</span><h2>{p.goal}</h2><p>{p.domain}</p></div><div className="controlState"><b>{p.active?"ACTIVE":"PAUSED"}</b><span>{p.dry_run?"Dry Run":"تنفيذ إنتاجي"}</span></div></section>
 <section className="controlGrid"><Panel title="🧠 العقل والقرار"><div className="stateRows"><Row k="حالة الدورة" v={auto?.status||"idle"}/><Row k="آخر تشغيل" v={auto?.last_run_id?`#${auto.last_run_id}`:"لم يبدأ"}/><Row k="الإصدار" v={auto?.release?.status||"لا يوجد"}/><Row k="قرار CEO" v={auto?.autonomy?.decision?.action||"لا يوجد قرار بعد"}/></div></Panel><Panel title="🎯 أهداف الشركة"><div className="goalList">{(auto?.autonomy?.goals||[]).map((g:any)=><div className="goal" key={g.name}><strong>{g.name}</strong><span>{g.metric} · {g.direction}</span><button onClick={()=>setMsg("تحرير الأهداف سيتم ربطه بمخزن أهداف الشركة في الدورة التالية.")}>تعديل</button></div>)}</div></Panel></section>
 <section className="controlGrid"><Panel title="👥 الموظفون"><div className="editableList">{s.employees.length?s.employees.map((e:any)=><div className="editableRow" key={e.id}><div><strong>{e.name}</strong><span>{e.role} · {e.agent||"agent"}</span></div><button disabled={busy} onClick={()=>toggleEmployee(e)}>{e.active?"إيقاف":"تفعيل"}</button></div>):<Empty text="لا يوجد موظفون. أضفهم من الإعدادات."/>}</div></Panel><Panel title="🤖 نماذج الذكاء"><div className="editableList">{s.models.length?s.models.map((m:any)=><div className="editableRow" key={m.id}><div><strong>{m.provider} · {m.model}</strong><span>{m.purpose}</span></div><button disabled={busy} onClick={()=>toggleModel(m)}>{m.active?"إيقاف":"تفعيل"}</button></div>):<Empty text="لا توجد نماذج. أضفها من الإعدادات."/>}</div></Panel></section>
 <section className="controlGrid"><Panel title="🔌 الصلاحيات والأدوات"><div className="toolMatrix">{Object.entries(s.connections||{}).filter(([k])=>k!=="secrets").map(([k,v])=><div key={k}><strong>{k}</strong><span className={v?"connected":"offline"}>{v?"متصل":"غير متصل"}</span></div>)}</div><a className="manageLink" href="/settings?tab=connections">إدارة الاتصالات والأسرار ←</a></Panel><Panel title="🚀 آخر Release"><div className="releaseBox"><strong>{auto?.release?.status||"لا يوجد release"}</strong><span>{auto?.release?.repository||"لم يتم إنشاء مستودع"}</span><span>{auto?.release?.pull_request?"Pull Request موجود":"لا يوجد Pull Request"}</span></div></Panel></section>
 </>}{edit&&<div className="editOverlay"><form className="editModal" onSubmit={e=>{e.preventDefault();saveProject()}}><div className="modalHead"><div><span className="eyebrow">EDIT PROJECT</span><h2>تعديل المشروع</h2></div><button type="button" className="close" onClick={()=>setEdit(null)}>×</button></div><label>اسم المشروع<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>النطاق<input value={edit.domain} onChange={e=>setEdit({...edit,domain:e.target.value})}/></label><label>GitHub repository<input value={edit.repo} onChange={e=>setEdit({...edit,repo:e.target.value})}/></label><label>Branch<input value={edit.branch} onChange={e=>setEdit({...edit,branch:e.target.value})}/></label><label>الهدف<select value={edit.goal} onChange={e=>setEdit({...edit,goal:e.target.value})}><option value="organic_traffic">زيادة الزيارات العضوية</option><option value="seo_growth">نمو SEO</option><option value="revenue">زيادة الأرباح</option><option value="content_growth">نمو المحتوى</option></select></label><label>اللغة<input value={edit.language} onChange={e=>setEdit({...edit,language:e.target.value})}/></label><label className="check"><input type="checkbox" checked={edit.dry_run} onChange={e=>setEdit({...edit,dry_run:e.target.checked})}/> تفعيل Dry Run</label><label className="check"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> المشروع نشط</label><button className="saveBtn" disabled={busy}>{busy?"جاري الحفظ…":"حفظ التعديلات"}</button></form></div>}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="controlPanel"><div className="panelHead"><h2>{title}</h2></div>{children}</section>}
function Row({k,v}:{k:string;v:string}){return <div className="stateRow"><span>{k}</span><strong>{v}</strong></div>}
function Empty({text}:{text:string}){return <div className="controlEmpty small">{text}</div>}
