"use client";

import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "https://autonomous-web-company-production.up.railway.app";

type SettingsData = {
  project: { id: number; name: string; domain: string; dry_run: boolean };
  employees: { id: number; name: string; role: string; agent: string; active: boolean }[];
  models: { id: number; provider: string; model: string; purpose: string; active: boolean }[];
  connections: { github: boolean; vercel: boolean; gsc: boolean; ga4: boolean; secrets: string[] };
};

async function json<T>(url: string, init?: RequestInit): Promise<T> { const r = await fetch(url, init); if (!r.ok) throw new Error(`${r.status} ${await r.text()}`); return r.json(); }

function Icon({ name, size = 18 }: { name: string; size?: number }) {
  const common = { width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round" as const, strokeLinejoin: "round" as const, "aria-hidden": true };
  const p: Record<string, React.ReactNode> = {
    grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.8 1.8 0 0 0 .3 2l.1.1-2 2-.1-.1a1.8 1.8 0 0 0-2-.3 1.8 1.8 0 0 0-1.1 1.6V21h-3v-.7a1.8 1.8 0 0 0-1.1-1.6 1.8 1.8 0 0 0-2 .3l-.1.1-2-2 .1-.1a1.8 1.8 0 0 0 .3-2 1.8 1.8 0 0 0-1.6-1.1H4v-3h.7a1.8 1.8 0 0 0 1.6-1.1 1.8 1.8 0 0 0-.3-2l-.1-.1 2-2 .1.1a1.8 1.8 0 0 0 2 .3A1.8 1.8 0 0 0 11 5.6V5h3v.6a1.8 1.8 0 0 0 1.1 1.6 1.8 1.8 0 0 0 2-.3l.1-.1 2 2-.1.1a1.8 1.8 0 0 0-.3 2 1.8 1.8 0 0 0 1.6 1.1h.6v3h-.6a1.8 1.8 0 0 0-1.6 1Z"/></>,
    plug:<><path d="M8 12h8M10 7V3M14 7V3"/><path d="M7 7h10v4a5 5 0 0 1-10 0V7ZM12 16v5"/></>,
    google:<><circle cx="12" cy="12" r="9"/><path d="M8 12h8M12 8v8"/></>,
    users:<><circle cx="9" cy="8" r="3"/><path d="M3 20v-1a5 5 0 0 1 10 0v1M16 11a3 3 0 1 0 0-6M16 14a5 5 0 0 1 5 5v1"/></>,
    brain:<><path d="M9 4.5A3 3 0 0 1 14 6a3 3 0 0 1 5 2.2A3 3 0 0 1 19 14a3 3 0 0 1-3 5 3 3 0 0 1-5 1.5A3 3 0 0 1 6 18a3 3 0 0 1-1-5 3 3 0 0 1 0-5A3 3 0 0 1 9 4.5Z"/><path d="M9 8v8M15 8v8M9 12h6"/></>,
    chart:<><path d="M4 19V5M4 19h16M7 15l3-4 3 2 5-7"/></>,
    activity:<path d="M3 12h4l2-7 4 14 2-7h6"/>,
    shield:<><path d="M12 3 20 6v5c0 5-3.4 8.4-8 10-4.6-1.6-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-4"/></>,
    arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>,
    globe:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></>,
  };
  return <svg {...common}>{p[name] || p.grid}</svg>;
}

export default function Settings() {
  const [projects,setProjects]=useState<any[]>([]),[pid,setPid]=useState<number>(),[s,setS]=useState<SettingsData>(),[tab,setTab]=useState("connections"),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  const [employee,setEmployee]=useState({name:"",role:"",agent:""}),[model,setModel]=useState({provider:"OpenAI",model:"gpt-5.6",purpose:"general"}),[secret,setSecret]=useState({provider:"",value:""});
  async function load(id?:number){try{setError("");const ps=await json<any[]>(`${API}/api/projects`);setProjects(ps);const next=id||pid||ps[0]?.id;if(next){setPid(next);setS(await json<SettingsData>(`${API}/api/projects/${next}/settings`));}}catch(e){setError(e instanceof Error?e.message:"Unable to load settings");}}
  useEffect(()=>{load()},[]);
  async function post(path:string,body:any){if(!pid)return;setSaving(true);try{setError("");await json(`${API}/api/projects/${pid}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load(pid);}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setSaving(false)}}
  const connected=s?[s.connections.github,s.connections.vercel,s.connections.gsc,s.connections.ga4].filter(Boolean).length:0;
  const tabs:[[string,string,string],[string,string,string],[string,string,string],[string,string,string]]=[["connections","Connections","plug"],["google","Google","google"],["employees","AI Workforce","users"],["models","AI Models","brain"]];
  return <div className="appShell">
    <aside className="sidebar"><div className="sideBrand"><div className="brandMark">A</div><div><strong>Autonomous</strong><span>Web Company</span></div></div><div className="sideSection">WORKSPACE</div><nav><a className="navItem" href="/"><Icon name="grid"/>Overview</a><button className="navItem" onClick={()=>setTab("employees")}><Icon name="users"/>Workforce</button><button className="navItem" onClick={()=>setTab("connections")}><Icon name="plug"/>Connections</button><button className="navItem" onClick={()=>setTab("models")}><Icon name="brain"/>AI Models</button><button className="navItem" onClick={()=>setTab("google")}><Icon name="chart"/>Google</button><a className="navItem" href="/"><Icon name="activity"/>Activity</a></nav><div className="sideBottom"><a className="navItem active" href="/settings"><Icon name="settings"/>Settings</a><div className="sideStatus"><i className="on"/><div><strong>Brain online</strong><span>{s?.project.dry_run===false?"Autonomous mode":"Dry Run mode"}</span></div></div></div></aside>
    <main className="mainArea settingsMain"><header className="topbar"><div><span className="eyebrow">SETTINGS</span><h1>Company configuration</h1><p>Connect the tools and AI workforce that let the Brain operate your company.</p></div><div className="topbarRight"><div className="live on"><i/>Brain online</div><a className="iconButton" href="/"><Icon name="arrow" size={16}/></a></div></header>
      {error&&<div className="alert"><span className="alertIcon">!</span>{error}</div>}
      <section className="settingsProject card"><div className="projectIdentity"><div className="projectIcon"><Icon name="globe"/></div><div><span className="eyebrow">ACTIVE PROJECT</span><h2>{s?.project.name||"Select a project"}</h2><a href={s?.project.domain?`https://${s.project.domain}`:undefined} target="_blank" rel="noreferrer">{s?.project.domain||"No project selected"} ↗</a></div></div><div className="settingsSummary"><div><strong>{connected}/4</strong><span>Tools connected</span></div><Badge on={!!s&&!s.project.dry_run} text={s?.project.dry_run===false?"Autonomous":"Dry Run"}/><select value={pid||""} onChange={e=>load(Number(e.target.value))}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></section>
      <nav className="settingsTabs">{tabs.map(([key,label,icon])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}><Icon name={icon}/><span>{label}</span></button>)}</nav>
      {tab==="connections"&&<section><SectionHead icon="plug" eyebrow="CONNECTIONS" title="Tools that power the Brain" text="Connect once. The Brain uses these integrations automatically for research, deployment and measurement."/><div className="connectionGrid"><ConnectionCard icon="plug" name="GitHub" description="Source control, repositories and autonomous code changes." on={!!s?.connections.github} action="Connect" onClick={()=>setTab("connections")}/><ConnectionCard icon="globe" name="Vercel" description="Deployments, production status and domain management." on={!!s?.connections.vercel} action="Connect" onClick={()=>setTab("connections")}/><ConnectionCard icon="chart" name="Search Console" description="Search performance, indexing and SEO opportunities." on={!!s?.connections.gsc} action="Configure" onClick={()=>setTab("google")}/><ConnectionCard icon="activity" name="Analytics 4" description="Users, sessions and engagement signals." on={!!s?.connections.ga4} action="Configure" onClick={()=>setTab("google")}/></div><div className="securityNote card"><div className="softIcon"><Icon name="shield"/></div><div><strong>Credentials stay protected</strong><p>Connection secrets are tested before saving and stored encrypted by the Brain. They are never displayed back in the dashboard.</p></div></div></section>}
      {tab==="google"&&<section><SectionHead icon="google" eyebrow="GOOGLE" title="Search & analytics" text="Give the Brain reliable measurement signals. It will use them to discover opportunities and evaluate changes."/><div className="googleGrid"><GoogleCard title="Search Console" icon="chart" status={!!s?.connections.gsc} text="Search queries, clicks, impressions and indexing signals."/><GoogleCard title="Google Analytics 4" icon="activity" status={!!s?.connections.ga4} text="Users, sessions and engagement signals."/></div><div className="card formPanel"><div className="panelTitle"><div className="softIcon"><Icon name="shield"/></div><div><h2>Secure Google credential</h2><p>Paste a service-account credential or approved project secret. The value is never rendered after save.</p></div></div><div className="formGrid"><label>Provider<input value={secret.provider} onChange={e=>setSecret({...secret,provider:e.target.value})} placeholder="google_service_account"/></label><label>Credential<input type="password" value={secret.value} onChange={e=>setSecret({...secret,value:e.target.value})} placeholder="Paste credential"/></label></div><div className="formActions"><span>Encrypted on save</span><button disabled={saving||!secret.provider||!secret.value} onClick={()=>post("/secrets",secret)}>{saving?"Saving…":"Save securely"}<Icon name="arrow" size={15}/></button></div></div></section>}
      {tab==="employees"&&<section><SectionHead icon="users" eyebrow="AI WORKFORCE" title="Build your autonomous team" text="Employees are AI agents with a role and model assignment. They can be orchestrated by the Brain without human operators."/><div className="card formPanel"><div className="formGrid three"><label>Name<input placeholder="SEO Analyst" value={employee.name} onChange={e=>setEmployee({...employee,name:e.target.value})}/></label><label>Role<input placeholder="Search intelligence" value={employee.role} onChange={e=>setEmployee({...employee,role:e.target.value})}/></label><label>Agent / model<input placeholder="gpt-5.6" value={employee.agent} onChange={e=>setEmployee({...employee,agent:e.target.value})}/></label></div><div className="formActions"><span>AI employee · not a human account</span><button disabled={saving||!employee.name||!employee.role} onClick={()=>post("/employees",employee)}>{saving?"Adding…":"Add employee"}<Icon name="arrow" size={15}/></button></div></div><div className="listPanel card"><div className="panelTitle"><div><h2>Current workforce</h2><p>Agents available to the Brain</p></div><span>{s?.employees.length||0} agents</span></div>{s?.employees.length?s.employees.map(e=><div className="workforceRow" key={e.id}><div className="avatarIcon"><Icon name="brain" size={16}/></div><div><strong>{e.name}</strong><span>{e.role}</span></div><small>{e.agent||"No model assigned"}</small><Badge on={e.active} text={e.active?"Active":"Paused"}/></div>):<EmptyState icon="users" title="No AI employees yet" text="Add your first role and the Brain can start assigning work to it."/>}</div></section>}
      {tab==="models"&&<section><SectionHead icon="brain" eyebrow="AI MODELS" title="Model routing" text="Define which AI providers and models the company can use for each kind of work."/><div className="card formPanel"><div className="formGrid three"><label>Provider<select value={model.provider} onChange={e=>setModel({...model,provider:e.target.value})}><option>OpenAI</option><option>Anthropic</option><option>Google</option><option>OpenRouter</option></select></label><label>Model ID<input value={model.model} onChange={e=>setModel({...model,model:e.target.value})} placeholder="Model ID"/></label><label>Purpose<select value={model.purpose} onChange={e=>setModel({...model,purpose:e.target.value})}><option>general</option><option>strategy</option><option>content</option><option>coding</option><option>analysis</option></select></label></div><div className="formActions"><span>Credentials are managed separately</span><button disabled={saving||!model.model} onClick={()=>post("/models",model)}>{saving?"Adding…":"Add model"}<Icon name="arrow" size={15}/></button></div></div><div className="listPanel card"><div className="panelTitle"><div><h2>Available models</h2><p>Models the Brain may route tasks to</p></div><span>{s?.models.length||0} models</span></div>{s?.models.length?s.models.map(m=><div className="modelRow" key={m.id}><div className="providerMark"><Icon name="brain" size={15}/></div><div><strong>{m.provider}</strong><span>{m.model}</span></div><em>{m.purpose}</em><Badge on={m.active} text={m.active?"Available":"Disabled"}/></div>):<EmptyState icon="brain" title="No models configured" text="Add a provider and model so the Brain can route work intelligently."/>}</div></section>}
      <footer><a href="/">← Back to Control Center</a></footer>
    </main>
  </div>;
}
function SectionHead({icon,eyebrow,title,text}:{icon:string;eyebrow:string;title:string;text:string}){return <div className="sectionTitle settingsSectionTitle"><div className="sectionTitleLead"><div className="softIcon"><Icon name={icon}/></div><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div></div></div>}
function Badge({on,text}:{on:boolean;text:string}){return <span className={`badge ${on?"good":"muted"}`}><i/>{text}</span>}
function ConnectionCard({icon,name,description,on,action,onClick}:{icon:string;name:string;description:string;on:boolean;action:string;onClick:()=>void}){return <div className="connectionCard card"><div className="connectionTop"><div className="softIcon"><Icon name={icon}/></div><Badge on={on} text={on?"Connected":"Not connected"}/></div><h3>{name}</h3><p>{description}</p><button className={on?"ghost":"primary"} onClick={onClick}>{on?"Manage":action}<Icon name="arrow" size={14}/></button></div>}
function GoogleCard({title,icon,status,text}:{title:string;icon:string;status:boolean;text:string}){return <div className="googleTool card"><div className="connectionTop"><div className="softIcon"><Icon name={icon}/></div><Badge on={status} text={status?"Connected":"Needs setup"}/></div><h3>{title}</h3><p>{text}</p><span className="toolHint">{status?"Brain can use live data":"Configure a credential below"}</span></div>}
function EmptyState({icon,title,text}:{icon:string;title:string;text:string}){return <div className="emptyState"><div className="emptyIcon"><Icon name={icon}/></div><strong>{title}</strong><p>{text}</p></div>}
