"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL||"https://autonomous-web-company-production.up.railway.app";
export default function Login(){
 const router=useRouter();const [signup,setSignup]=useState(false);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [name,setName]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(`${API}/api/auth/${signup?"signup":"login"}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(signup?{email,password,name}:{email,password})});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:"authentication_failed"}))).detail||"authentication_failed");router.push("/");router.refresh()}catch(err){setError(err instanceof Error?err.message:"authentication_failed")}finally{setBusy(false)}}
 return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"#07111d"}}><section style={{width:"100%",maxWidth:460,padding:32,border:"1px solid rgba(255,255,255,.12)",borderRadius:20,background:"rgba(15,27,43,.92)",color:"white"}}><div style={{fontSize:12,letterSpacing:2,opacity:.7}}>AUTONOMOUS WEB COMPANY</div><h1 style={{fontSize:32,margin:"10px 0 8px"}}>{signup?"إنشاء حساب":"تسجيل الدخول"}</h1><p style={{opacity:.7}}>حسابك هو بوابة الوصول إلى مشاريع الشركة وبياناتها.</p><form onSubmit={submit} style={{display:"grid",gap:14,marginTop:24}}>{signup&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="الاسم" required minLength={2}/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني" type="email" required/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة المرور (12 حرفًا على الأقل)" type="password" required minLength={12}/>{error&&<div style={{color:"#ff8f8f"}}>{error}</div>}<button disabled={busy} type="submit">{busy?"جاري التنفيذ…":signup?"إنشاء الحساب":"دخول"}</button></form><button onClick={()=>setSignup(!signup)} style={{marginTop:16,background:"none",border:0,color:"inherit",opacity:.75}}>{signup?"لدي حساب بالفعل":"إنشاء حساب جديد"}</button></section></main>
}
